version: "3.9"
name: geoflow_upd
services:
  pgdb_upd:
    build: ./db

    container_name: pgdb_upd
    volumes:
      - ./data:/data
      - ./data/pg_db:/var/lib/postgresql/data
    env_file:
      - ./pgdb/pg.env

    ports:
      - 5420:5432
  geoflow-dim:
    #image: geoflow-dim
    build: ./
    volumes:
      - ./config:/config
      - ./example_data/10_268_594/bati_ign:/data/poly
      - ./example_data/10_268_594/las_in/:/data/laz/ahn3
      - ./tmp:/tmp
      - ./output:/data/output
      - ./resources/:/dim_pipeline/resources
      - ./run.py/:/dim_pipeline/run.py
    environment:
      PG_OUTPUT: ${PG_OUTPUT}
    tty: true

  pg_3d_upd:
    build: ./pg3d
    tty: true
    container_name: pg_3d_upd

    volumes:
      - ./data:/data

    ports:
      - 5600:5600
    depends_on:
      - pgdb_upd
